name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 23f3001731@ds.study.iitm.ac.in
        run: echo "Hello, world!"
        
